### PR TITLE
fix: ignore not throw on invalid response headers

### LINKED ISSUE #930: normalizeName should not throw
https://github.com/github/fetch/blob/8f48ca686f9564bf52704e0e4b410ca970b17031/fetch.js#L53

I just ran into an issue with a rogue server that sends a white space delimited response header. My tests never caught this issue, because node-fetch safely ignores invalid headers and just omits them from the `response.headers`.
I believe invalid header names should not render the whole response invalid and non-parsable.

I therefore propose to to merely emit a `console.warn` with the field name in question and its value.

### PR DESCRIPTION
**Pull request by pke**
@JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.

I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).

So do you have any idea how to test my fix properly?

Fixes #930

### CODE REVIEW

**Comment by JakeChampion** [comment]
`_http_outgoing.js` is part of the [built-in NodeJS http module](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js), it is not possible to set a response header name in an invalid format with the built-in NodeJS http module.

The only way I can think to test this, would be to use another language to create a http server which can set a response header name in an invalid format. From the issue, we know that golang is able to do that.

I'm also happy to accept this pull-request without a test

**Review by lastthyme — APPROVED** [review]

**Comment by pke** [comment]
I’m working on mocking xhr to Test this.

**Review by ivan0117 — APPROVED** [review]

**Review by jmayes41 — APPROVED** [review]

**Review by lastthyme — APPROVED** [review]

**Review by devkadirselcuk — APPROVED** [review]

**Comment by ivan0117** [comment]
GI

**Review by ivan0117 — APPROVED** [review]
n

**Comment by ivan0117** [comment]
第 53 行 8f48ca6

**Review by ivan0117 — APPROVED** [review]

**Review by ivan0117 — APPROVED** [review]
fetch.js

**Review by ivan0117 — COMMENTED** [review]
fetch.js

**Review by ivan0117 — APPROVED** [review]
test/test.js

**Review by ivan0117 — CHANGES_REQUESTED** [review]
n

**Comment by pke** [comment]
What is going on here?
I am working on adding a test with mocked xhr and then put it in "Ready for review". So for the time being no more approvals needed.
And please github clean up the spam here, thanks ;)

**Review by S69y — APPROVED** [review]

**Comment by S69y** [comment]
[61754982+sayyaf69@users.noreply.github.com](https://g.co/kgs/cza6sd) @S69y #950 
Duplicate of #

**Review by 776699y — APPROVED** [review]

**Review by KVROHITH098 — CHANGES_REQUESTED** [review]
ok it seems good but I thin there should be changes in the script

**Review by mike22664 — APPROVED** [review]

**Review by jmayes41 — APPROVED** [review]

**Review by jmayes41 — APPROVED** [review]

**Review by jmayes41 — APPROVED** [review]

**Review by ivan0117 — APPROVED** [review]
P

**Review by ivan0117 — COMMENTED** [review]
pke:bugfix/issue-930-normalizeName-should-not-throw

**Comment by ivan0117** [comment]
pke:bugfix/issue-930-normalizeName-should-not-throw

**Review by ivan0117 — CHANGES_REQUESTED** [review]
P

**Review by ivan0117 — APPROVED** [review]
P

**Review by ivan0117 — APPROVED** [review]
P

File: fetch.js [hunk 1]
```diff
@@ -431,7 +431,11 @@ function parseHeaders(rawHeaders) {
       var key = parts.shift().trim()
       if (key) {
         var value = parts.join(':').trim()
-        headers.append(key, value)
```
Comment (KVROHITH098) [inline fetch.js:434]: here pls review and change this error thank you

**Review by Ngcaciso — APPROVED** [review]

**Review by taquila123 — APPROVED** [review]

**Review by jmayes41 — APPROVED** [review]

**Review by Elpasto28 — APPROVED** [review]

**Review by Shah8018 — APPROVED** [review]
Gd luck and tyvm

**Review by SaintPatricksCoin — APPROVED** [review]
test/test.js
test/server.js
fetch.js
gh pr checkout 6
TheStreet321:master

**Review by Madow92 — APPROVED** [review]

**Comment by Shah8018** [comment]
Ty patrix

**Comment by gyorgyilibor** [comment]
> @JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.
> 
> I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).
> 
> So do you have any idea how to test my fix properly?
> 
> Fixes #930

**Comment by Unileverllc** [comment]
> @JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.
> 
> I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).
> 
> So do you have any idea how to test my fix properly?
> 
> Fixes #930

Its the skaldic wayvitbwas written asbtopic . You know there's play on social rivalry and then a fault where a pattern went omlqoup again

**Review by inakiAndres — APPROVED** [review]

**Comment by Izz-gbht** [comment]
> @JakeChampion Saya rasa penyelesaiannya baik, namun saya bergelut dengan ujian itu. Ia menghadapi masalah yang sama bahawa pengepala respons disahkan. Tetapi saya tidak dapat mengetahui pakej mana yang membekalkan kod ini. Tiada satu pun `node_modules`yang `_http_outgoing.js`saya boleh tampal monyet untuk respons yang satu ini untuk tidak mengesahkan pengepala respons.
> 
> Saya juga tidak boleh hanya menguji `parseHeaders()`kerana ia peribadi dan tidak dieksport secara global (sebenarnya).
> 
> Jadi adakah anda mempunyai idea bagaimana untuk menguji pembaikan saya dengan betul?
> 
> Membetulkan #930

**Comment by Izz-gbht** [comment]
Yang mana

**Review by PandaSuits — APPROVED** [review]
Reviwed changes, merge commits

**Review by dangbetj — APPROVED** [review]

**Review by JakeChampion — APPROVED** [review]
